# job 1
#2.1.18.RELEASE,
#2.0.9.RELEASE,
# step 1
# step 2
# step 3
# step 4
## step 4.1: for Ubuntu and MacOS
## step 4.2: for Windows
# job 2
# step 1
# step 2
# step 3
# step 4
## step 4.1: for Ubuntu and MacOS
## step 4.2: for Windows

name: Modified test
jobs:
  test:
    name: test (${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.springboot }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - macos
        - windows
        springboot:
        - 2.7.18         -D spring-framework.version=5.3.31
        - 2.6.15         -D spring-framework.version=5.3.27
        - 2.5.15         -D spring-framework.version=5.3.27
        - 2.4.13         -D spring-framework.version=5.3.13
        - 2.3.12.RELEASE -D spring-framework.version=5.2.15.RELEASE
        - 2.2.13.RELEASE -D spring-framework.version=5.2.12.RELEASE
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test (${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.springboot }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/incubator-seata/incubator-seata', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Checkout
      uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Use Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - run: touch optcd-4.txt
    - name: Set up Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - run: touch optcd-5.txt
    - name: Test with Maven on '${{ matrix.os }}' OS
      run: |-
        if [ "${{ matrix.os }}" == "macos" ]; then
           python3 -m ensurepip --upgrade;
           python3 -m pip install --upgrade pip setuptools;
           if ! python3 -c "import distutils" &>/dev/null; then
              python3 -m pip install --upgrade setuptools
           fi
          ./mvnw -T 4C clean test -P args-for-client-test  -P arrch64 -Dspring-boot.version=${{ matrix.springboot }} -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
        else
          ./mvnw -T 4C clean test -P args-for-client-test -Dspring-boot.version=${{ matrix.springboot }} -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
        fi
    - run: touch optcd-6.txt
    - name: Build with Maven on 'windows' OS (Skip tests)
      run: |-
        ./mvnw.cmd -version;
        ./mvnw.cmd clean install -P args-for-client-test -DskipTests -D spring-boot.version=${{ matrix.springboot }} -e -B -D org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test (${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.springboot
          }})
        path: /home/runner/inotifywait-log-test (${{ matrix.java }}, ${{ matrix.os
          }}, ${{ matrix.springboot }}).csv
  test-springboot3x:
    name: test-springboot3x (${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.springboot
      }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        java:
        - 17
        - 21
        os:
        - macos
        - windows
        springboot:
        - 3.2.0  -D spring-framework.version=6.1.1
        - 3.1.6  -D spring-framework.version=6.0.14
        - 3.0.13 -D spring-framework.version=6.0.14
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test-springboot3x (${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.springboot }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/incubator-seata/incubator-seata', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Checkout
      uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Use Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - run: touch optcd-4.txt
    - name: Set up Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - run: touch optcd-5.txt
    - name: Test with Maven on '${{ matrix.os }}' OS
      run: |-
        if [ "${{ matrix.os }}" == "macos" ]; then
           python3 -m ensurepip --upgrade;
           python3 -m pip install --upgrade pip setuptools;
           if ! python3 -c "import distutils" &>/dev/null; then
              python3 -m pip install --upgrade setuptools
           fi
          ./mvnw -T 4C clean test -P args-for-client-test  -P arrch64 -Dspring-boot.version=${{ matrix.springboot }} -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
        else
          ./mvnw -T 4C clean test -P args-for-client-test -Dspring-boot.version=${{ matrix.springboot }} -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
        fi
    - run: touch optcd-6.txt
    - name: Build with Maven on 'windows' OS (Skip tests)
      run: |-
        ./mvnw.cmd -version;
        ./mvnw.cmd clean install -P args-for-client-test -DskipTests -D spring-boot.version=${{ matrix.springboot }} -e -B -D org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test-springboot3x (${{ matrix.java }}, ${{ matrix.os }},
          ${{ matrix.springboot }})
        path: /home/runner/inotifywait-log-test-springboot3x (${{ matrix.java }},
          ${{ matrix.os }}, ${{ matrix.springboot }}).csv
'on':
- push
- workflow_dispatch
